apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
rules:
- apiGroup: [""]
  resources: ["nodes"] # or resources: ["namespaces"]
  verbs: ["get", "create", "list", "delete", "update"]
