apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # namespace: [specific ns scope]
  name: developer
rules:
- apiGroup: [""]
  resources: ["pods"]
  verbs: ["get", "create", "list"]
  # resourceNames: ["scope pods name"]
- apiGroup: [""]
  resources: ["secrets"]
  verbs: ["get"]
  # resourceNames: ["scope secrets name"]