appName: servicename
appImage: un4ckn0wl3z/servicename
appVersion: v.0.0.0
appReplicas: 1
containerPort: 8080
containerEnvVar:
- name: ENV_VAR_ONE
  value: "valueone"
- name: ENV_VAR_TWO
  value: "valuetwo"

serviceType: ClusterIP
servicePort: 8080